### ISSUE TITLE
Genesis error when trying to use Events

### ISSUE THREAD

**Issue by HollowGraphic** [jeffcampbellmakesgames/Entitas-Redux#10]
Adding `[Event()]` attribute to any component causes Genesis to fail with an error stating "Value cannot be null. Parameter name: element"

**Comment by jeffcampbellmakesgames** [comment]
@HollowGraphic Can you post an example of the component that's experiencing this issue with the full stacktrace of the error please? I see that there is an event component example and when testing code-generation currently this does not result in any issues.

**Comment by HollowGraphic** [comment]
`             [Event(EventTarget.Self, EventType.Added)]
             [Event(EventTarget.Self, EventType.Removed)]
             [Game]
             public class Active : IComponent { }`

Trace:
 

- [JCMG.Genesis.Editor.UnityCodeGenerator] [Genesis] Code generation failed, process exited with code {0}.
  at JCMG.Genesis.Editor.UnityLogger.Log (JCMG.Genesis.Editor.LogLevel logLvl, System.String message, System.Exception exception) [0x00052] in 

- F:\Train Builder\Library\PackageCache\com.jeffcampbellmakesgames.genesis@1.2.0\Scripts\Editor\Logging\UnityLogger.cs:102 

  at JCMG.Genesis.Editor.UnityLogger.Warn (System.String message) [0x00000] in

-  F:\Train Builder\Library\PackageCache\com.jeffcampbellmakesgames.genesis@1.2.0\Scripts\Editor\Logging\UnityLogger.cs:59 

  at JCMG.Genesis.Editor.UnityCodeGenerator.Generate (JCMG.Genesis.Editor.GenesisSettings[] settingsData) [0x000f2] in
 

- F:\Train Builder\Library\PackageCache\com.jeffcampbellmakesgames.genesis@1.2.0\Scripts\Editor\CodeGeneration\UnityCodeGenerator.cs:134 

  at JCMG.Genesis.Editor.UnityCodeGenerator.GenerateAll () [0x00005] in

- F:\Train Builder\Library\PackageCache\com.jeffcampbellmakesgames.genesis@1.2.0\Scripts\Editor\CodeGeneration\UnityCodeGenerator.cs:48 

  

- at JCMG.Genesis.Editor.MenuItems.ExecuteGenesisCodeGeneration () [0x00000] in

 F:\Train Builder\Library\PackageCache\com.jeffcampbellmakesgames.genesis@1.2.0\Scripts\Editor\MenuItems.cs:72

**Comment by jeffcampbellmakesgames** [comment]
I can see two issues here:

* The Genesis code generation library doesn't give enough information to act on when an exception in a code generator occurs. https://github.com/jeffcampbellmakesgames/Genesis/issues/4 has been created to handle this.
* There is an bug retrieving component names for a validation step where the component type did not previously exist. 

The fix for this should be pretty straightforward for both; as far as an ETA I'll see if I can knock this out later tonight and post an updated package for both Genesis and EntitasRedux. This will require updating your package to the latest at that point.

**Comment by HollowGraphic** [comment]
Sweet, I'll keep an eye out

**Comment by jeffcampbellmakesgames** [comment]
Both of these issues have been resolved for Genesis and EntitasRedux and a new version v1.2.2 is available that should resolve these issues. Let me know how this works for you!

**Comment by HollowGraphic** [comment]
Awesome, I'll keep you posted.

**Comment by HollowGraphic** [comment]
No errors. All event systems and components are being generated.

**Comment by jeffcampbellmakesgames** [comment]
> No errors. All event systems and components are being generated.

Excellent. I am closing this out as complete then.
