### ISSUE TITLE
[BUG] Entitas Redux installation link on wiki page is broken

### ISSUE THREAD

**Issue by matthiashermsen** [jeffcampbellmakesgames/Entitas-Redux#36]
**Describe the bug**
The main README file shows the correct git installation urls

https://github.com/jeffcampbellmakesgames/entitas-redux#install-via-git-url

but the wiki page has a broken url for the Entitas Redux package

https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Installation#install-via-git-url

There is missing a hyphen between "entitasredux".

**Expected behavior**
Instead of

> "com.jeffcampbellmakesgames.entitasredux" : "https://github.com/jeffcampbellmakesgames/entitasredux.git#release/stable"

I would expect this

> "com.jeffcampbellmakesgames.entitasredux" : "https://github.com/jeffcampbellmakesgames/entitas-redux.git#release/stable"

**Additional context**
Suggestion:

- Fix the wiki page
- Remove the installation guide from the main README file
- Refer to the wiki page in the main README file

**Comment by matthiashermsen** [comment]
Fixed the wiki page, revision:

https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Installation/_compare/8503a422e7d3d18cb24ae121bffb18ed7ca887be

@jeffcampbellmakesgames you can either close this or have a look at the suggestion

- Remove the installation guide from the main README file
- Refer to the wiki page in the main README file

your choice :)

**Comment by jeffcampbellmakesgames** [comment]
I'm going to leave this open for the moment, but once I can identify a good landing spot for a new user navigating from the readme to the wiki I will effect that change and close this.

**Comment by jeffcampbellmakesgames** [comment]
@matthiashermsen I've updated the readme to point to the https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Getting-Started page for installation and getting started instructions and removed the older content for installing on the readme.
