### ISSUE TITLE
[FEATURE REQUEST] Add wiki page on how to setup a complete repository

### ISSUE THREAD

**Issue by matthiashermsen** [jeffcampbellmakesgames/Entitas-Redux#38]
**Is your feature request related to a problem? Please describe.**
Currently there is a Hello World wiki page covering the basics. It would be nice to have a guide covering a complete setup e.g. for "teams" working with Git and automated tests.

**Describe the solution you'd like**
It would be nice to have a wiki page covering the following parts:
- [x] Prerequisites
- [x] How to setup the Git repository
- [x] How to setup the .gitignore file
- [x] How to setup the Unity project for that repository
- [x] How to setup Entitas-Redux for that Unity project
- [x] Simple code example
- [x] How to setup the tests

**Describe alternatives you've considered**
Entitas experts might create more complex examples e.g. how to create a "Pong" with Entitas-Redux.

**Comment by matthiashermsen** [comment]
I would like to work on this. Please ping me if you want me to :)

**Comment by jeffcampbellmakesgames** [comment]
Hi @matthiashermsen, I apologize for the delayed response; after I move on Dec 18th I will be able to be more responsive and my general engagement for this framework will be picking up.

I am more than happy to make it easier for the community to update the wiki. As a goal for myself I'd like to be able to check in on the changes over time to make sure the information is accurate and conveyed well. For now I have opened up the wiki so that it is editable by the public which should give you the access you desire. If I need to limit this access in the future I will make that known in advance and work with those interested in updating the content to make sure they still retain that ability. 

Thanks for your interest in this project and expressing interest in making this easier for developers to use! I'll check in later this month and see if there is any helpful feedback or direction I can give with regards to the content, but your checklist items listed so far seem reasonable.

**Comment by matthiashermsen** [comment]
@jeffcampbellmakesgames np! take your time :)

I will try to create a page in some days and let you know, so you can review it if you want

**Comment by matthiashermsen** [comment]
The new wiki page can be found here

https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/How-to-setup-a-new-Github-project-with-tests

@jeffcampbellmakesgames please review it whenever you want :)

Please also have a look at my changes here

https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Installation#install-via-git-url 

~~The new wiki page still needs to be added to the page list, I don't know where to put it.~~

**Comment by jeffcampbellmakesgames** [comment]
Hey @matthiashermsen, thanks for digging into this further. Now that I'm moved in and have internet again I am catching up on ER work and your updates to the wiki. Will get back to you shortly

**Comment by matthiashermsen** [comment]
I also added "back to top" links, I think this is better for fast navigation :)

**Comment by jzapdot** [comment]
I'll have some time this weekend for ER, but I wanted to share some general feedback. Overall looks great, but a few specific thoughts arose as I read through the tutorial that I wanted to get your thoughts on:

I think that this tutorial does a better job of covering Hello World than the page I created which covers more of an introduction to ECS and ER concepts. I'd like to at minimum rename the titles to match, but another thought is that it might be worth breaking up this tutorial into two; one for basic Unity project setup and the other which would be focused more specifically on a simple Hello World tutorial after the project is setup.

I would make this section on adding a `.gitignore` smaller and more generic. This is one of those areas that teams customize a great deal based on their own preferences. It'd be less confusing for a new user overall if we pointed them to the GitHub Unity `.gitignore` as a general step in setting up their project and not delve into any specifics that might be based on taste or style.

There is a lot of great content here for testing that feels like it's large enough that it would be worth removing into its own section separate from a Getting Started or Project Setup page, perhaps with more of a contextual bent on best practices for unit-testing EntitasRedux. It might be worth also adding unit test setup information for those using the test runner with native Unity support (*NUnit*) as not everyone might be using **Rider** or **XUnit**.

**Comment by matthiashermsen** [comment]
> I think that this tutorial does a better job of covering Hello World than the page I created which covers more of an introduction to ECS and ER concepts. I'd like to at minimum rename the titles to match, but another thought is that it might be worth breaking up this tutorial into two; one for basic Unity project setup and the other which would be focused more specifically on a simple Hello World tutorial after the project is setup.

Yes, I think we could / should split it into multiple pages :)

> I would make this section on adding a .gitignore smaller and more generic. This is one of those areas that teams customize a great deal based on their own preferences. It'd be less confusing for a new user overall if we pointed them to the GitHub Unity .gitignore as a general step in setting up their project and not delve into any specifics that might be based on taste or style.

Yes, that's true. I just discovered some optimizations so I added them to the .gitignore template. (e.g. ignore the Unity project .sln file because there is no need to add it to the version.

> There is a lot of great content here for testing that feels like it's large enough that it would be worth removing into its own section separate from a Getting Started or Project Setup page, perhaps with more of a contextual bent on best practices for unit-testing EntitasRedux. It might be worth also adding unit test setup information for those using the test runner with native Unity support (NUnit) as not everyone might be using Rider or XUnit.

True

---

@jeffcampbellmakesgames Yes, we should split that tutorial. I would suggest the following modifications to the wiki:

- [ ] Remove wiki content from the main README file => see #36 
- [ ] Complete missing page for [Entity-Indexes](https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Entity-Indexes)
- [ ] Complete missing page for [Groups](https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Groups)
- [ ] Complete missing page for [Systems](https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Systems)

~~- [x] How to setup a git repository for Unity~~ (no need for that)

- [x] Installation (can be found [here](https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Installation) )
- [x] Genesis Setup (Below installiation, see #41 )
- [ ] Essential ECS Concepts (Add it to [this page](https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Concepts) )
- [ ] Change the [Hello World page](https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Hello-World) to a minimum and refer to the other pages for setup
- [ ] How to test your project using the Unity Test Runner (currently with NUnit) | no need to do it like this anymore https://www.youtube.com/watch?v=DZpvUnj2dGI
- [ ] Add pages for best practises e.g.
    - Scene management
    - Communication between ER and Unity
    - Layer abstraction if needed
    - ...

**Comment by jzapdot** [comment]
@matthiashermsen This all looks good to me for a next pass; ` Genesis Setup (Below installiation)` is likely to change in the near future since Genesis v2 is going to be coming.

>  How to test your project using the Unity Test Runner (currently with NUnit) | no need to do it like this anymore https://www.youtube.com/watch?v=DZpvUnj2dGI

Exactly, there is a test runner in Unity now and tests can be run from the Editor as well as many IDEs.

**Comment by matthiashermsen** [comment]
Closing this in favor of the docs board

https://github.com/jeffcampbellmakesgames/Entitas-Redux/projects/3
