### ISSUE TITLE
[Docs] Document Genesis Setup (Below installation)

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [jeffcampbellmakesgames/Entitas-Redux#41]
**Is your feature request related to a problem? Please describe.**
Create or reuse existing documentation for Genesis Setup to own section under installation on the wiki

**Comment by matthiashermsen** [comment]
@jeffcampbellmakesgames I would like to work on this :)

**Comment by matthiashermsen** [comment]
@jeffcampbellmakesgames Please review this

https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/Genesis-Setup

I also added the page to the wiki sidebar

https://github.com/jeffcampbellmakesgames/Entitas-Redux/wiki/_Sidebar/_compare/e48c39f1dd2bd6a95c78514adc8e6082a7a05d95

**Comment by jeffcampbellmakesgames** [comment]
Looks good! I made some minor changes, added some screenshots, and created a Getting Started section so it was clearer in that part of the sidebar that installation and genesis setup were related. If you're happy with how this looks and reads I would mark this as complete.

**Comment by matthiashermsen** [comment]
Yes, this is fine :) 
You can close this
