### ISSUE TITLE
[QUESTION] How to setup a new assembly definition asset without loosing access to the generated code?

### ISSUE THREAD

**Issue by matthiashermsen** [jeffcampbellmakesgames/Entitas-Redux#55]
I'm using Unity 2020.3.13f1 want to setup an assembly definition asset to pass it as a reference to the Play/Edit mode tests. 

- Install .Net Core 3.1
- Create a new  project
- `Project Settings` => `Player` => Change the API compability level to .NET 4.x (for PC, Android and HTML)
- Install the packages via `openupm add com.jeffcampbellmakesgames.entitasredux`
- Create a folder right next to the `Assets` folder and name it `Genesis.CLI`
- `Project Settings` => `Genesis` => Set this folder as the Genesis installation folder by selecting it

![image](https://user-images.githubusercontent.com/47159597/125206159-f7272e80-e285-11eb-94e7-ede5a1862b59.png)

- Click the button "Update Genesis CLI"
- Click the button "Install or Update All Plugins"
- Create new `GenesisSettings` inside `Assets/Sources` via context menu => `Create` => `JCMG` => `Genesis` => `GenesisSettings`

![image](https://user-images.githubusercontent.com/47159597/125206245-8e8c8180-e286-11eb-9fd9-c5feeeb6bc36.png)

- Open the `GenesisSettings.asset` in the inspector
- Click the button "Auto Import"
- Change the output directory to `Assets/Sources/Generated`
- Click the button "Generate"
- Create a new component `Assets/Sources/Features/AComponent.cs` with the content

```cs
using JCMG.EntitasRedux;

namespace Sources.Features
{
    [Game]
    public sealed class AComponent : IComponent { }
}
```

![image](https://user-images.githubusercontent.com/47159597/125206395-5f2a4480-e287-11eb-9b3d-5b357c85cdd4.png)

- Generate the code again

Everything should be fine for now. You can find a stable version in this temporary reproduction repository branch

https://github.com/matthiashermsen/er-namespace-reproduction

Since I want to setup unit tests I have to create the assembly definition asset. To ensure all the code is picked up I created it here `Asset/Sources/Sources.asmdef` with this setup

![image](https://user-images.githubusercontent.com/47159597/125206636-89c8cd00-e288-11eb-944d-67dda32b0bcb.png)

Compile errors come up

![image](https://user-images.githubusercontent.com/47159597/125206648-a36a1480-e288-11eb-83bc-b7cef8b3173f.png)

I tried to generate the code again but unfortunately the errors remain. I pushed the broken version on this branch

https://github.com/matthiashermsen/er-namespace-reproduction/tree/broken

I would like to know how to solve this problem

- Is there a way the Play/Edit mode test assembly definitions don't require the sources assembly definition?
- Are there any configurations for ER / Genesis?
- Is it not possible to use namespaces with Genesis when using the built in Unity test framework?

**Comment by jeffcampbellmakesgames** [comment]
I don't think this is as much a question specific to ER than it is a general Unity question on how to use AssemblyDefinitions.

If you don't use AssemblyDefinitions, everything gets put into an appropriate auto-generated C# project based on whether it's runtime or editor code. All runtime code for example gets placed automatically for example in the `CSharp-Assembly` project if not in an AssemblyDefinition. EntitasRedux's own AssemblyDefinitions are auto-referenced by these C# Projects by Unity as part of it's auto-generated process.

If an AssemblyDefinition is created, it will only reference the AssemblyDefinitions the developer explicitly adds. That means unless the EntitasRedux AssemblyDefinitions are explicitly added, you will have compiler errors. 

Using your example branch I created the same Sources AssemblyDefinition, added the EntitasRedux runtime AssemblyDefinitions, and hit Apply which resolved all open compiler errors. 

![image](https://user-images.githubusercontent.com/1663648/125209042-317fd400-e264-11eb-8a49-4518fae3ee58.png)

**Comment by matthiashermsen** [comment]
I'm sorry, I didn't know that. Thanks a lot!
