### ISSUE TITLE
Is Entitas-Redux still maintained and are there any future plans?

### ISSUE THREAD

**Issue by jtuchel** [jeffcampbellmakesgames/Entitas-Redux#58]
First of all thanks for the work on this project, it looks really nice. I would like to know if this project is still maintained / under development? I've seen that Entitas received some commits after long time but I think Entitas-Redux offers a great benefit for "Unity-only" users :)

There is a roadmap so I'm not sure if the open issues have a high priority?

Do you have any plans creating a sample game like these https://github.com/sschmid/Entitas-CSharp/wiki/Example-projects#other-entitas-examples ? ( which unfortunately are "outdated" )

Thanks in advance!

**Comment by jeffcampbellmakesgames** [comment]
Hi @jtuchel,

I do maintain this project although active development from myself comes in fits and bursts as I have time to add new features. Development also comes in parallel with using it on various side projects and at the moment I am not using it (yet). In my full-time work we have been very busy with client projects and do not use ER yet, but there are several future or nascent projects I have my eye on that would benefit from it and in that case there would likely more updates for general fixes and features we'd like to make available to the community.

I do accept PRs for bug fixes or new features, but so far this has not been frequent which may be why it seems like there are few updates in general. I have recently made a few fixes to Genesis in response to a user-submitted bug which will bubble up as updates for ER (https://github.com/jeffcampbellmakesgames/Entitas-Redux/issues/62). If there is more community interest in developing new features or fixes I am happy to lend my support and expertise as available.

**Comment by jtuchel** [comment]
thanks!

I think if ER might be feature-complete focusing on the wiki pages for beginners like me would be awesome
