### ISSUE TITLE
[BUG] Problems with using Redux

### ISSUE THREAD

**Issue by WeslomPo** [jeffcampbellmakesgames/Entitas-Redux#59]
**Describe the bug**
Hi! Struggling with starting to use a Entitas-Redux.
I following a documentation from wiki, and stumbling over uncertain things.
First problem, that I encounter is this:
![image](https://user-images.githubusercontent.com/310008/146243246-93add065-2941-4577-8ca8-cf365182399f.png)
`Library\PackageCache\com.jeffcampbellmakesgames.entitasredux@6eb819129f\Scripts\EntityLink.cs(47,4): error CS1705: Assembly 'EntitasRedux.Core' with identity 'EntitasRedux.Core, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null' uses 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'netstandard' with identity 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

I solved this by changing "Api compability level" to ".NET 4.x". Honestly, I thinking that is a strange problem, but my project is just experiment, so, I don't bothered about it. But this need to be specified in docs, or don't use net over 2.0, or I just probably dumb.

Second problem.
I return to rails, that I follwed, and somehow installed Genesis. But when I trying to auto-import, I got this:
![image](https://user-images.githubusercontent.com/310008/146244246-79ae9de2-6dc7-42f1-af40-1e0c5cfd29d8.png)
Yeah! Unreadable symbols! Thanks windows for your code page >__<, this does not looks like russian xD and I can't read it either. 
I was struggling at first, but then remember that when I was installing a Entitas vanila - I have similiar problem! I do not have `dotnet` in my OS. So! I have suggestion, to add this problem in Wiki (that user need to install necore sdk >=2.0).

Third problem.
Installing dotnet - does not help xD. Problem still occurs, but it works from cmd, for now idk what to do...

**Unity Version:**
_Unity 2020.3.22f1_
**OS Version**
Windows 10

**Comment by WeslomPo** [comment]
Restarting compukter are helped :)

**Comment by jeffcampbellmakesgames** [comment]
Hi @WeslomPo,

I'm sorry you were having issues getting ER up and running. For future reference on the readme [here](https://github.com/jeffcampbellmakesgames/Entitas-Redux#requirements) the requirements are noted for .Net 4.X and for .Net Core 3.1 to be installed. I do see on the wiki that the .Net Core 3.1 requirement was missing there and so have added it to now reflect what the readme states. I hope this makes using ER easier for you in the future.
