### ISSUE TITLE
[BUG] maybe need update v2.1.2 Entitas-Redux-Plugins version

### ISSUE THREAD

**Issue by vkensou** [jeffcampbellmakesgames/Entitas-Redux#63]
**Describe the bug**
When i click "Auto Import" on Genesis Settings Inspector, I have some warning report: 
 [2.4.4.0] [Warning] Assembly "EntitasRedux.Core.Plugins" at v"2.1.2.0" references an out-of-date version of "Genesis.Plugin" at v"2.3.2.0" and won't be loaded.

**Unity Version:**
_Unity 2020.3.23f

**Comment by vkensou** [comment]
version v2.1.1  is ok

**Comment by jeffcampbellmakesgames** [comment]
The latest version `v2.1.3` should be synced for both Genesis and ER plugin versions
